modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/AshIndigo/Mail-Mod/issues"
license = "MIT"

[[mods]]
modId = "mail"
version = "${version}"
displayName = "Mail"
authors = "AshIndigo"
description = '''
Mod for sending and receiving items from other players on a server
'''
logoFile = "icon.png"

[[dependencies.mail]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mail]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mail]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"