modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mailmod"
version = "${version}"
displayName = "Mail Mod"
authors = "AshIndigo"
description = '''
Mod for sending and receiving items from other players on a server
'''
#logoFile = ""

[[dependencies.mailmod]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mailmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mailmod]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"